### PR TITLE
Added support  for Node 10.16.3 patch

### PR DESCRIPTION
**Pull request by MrSmallLiu**
Add Node.js v10.16.3 patch file,update patches.json to support Node.js v10.16.3

### CODE REVIEW

**Comment by punisher97** [comment]
Thanks for you patch, i need v10.16.3 to compile with tfjs-node properly, thanks, i share my binary to windows x64
https://drive.google.com/open?id=17bFBE7MOi2VXfUbwJEV0WnjbNzMGdxa3

**Comment by bruvv** [comment]
@igorklopov please merge

**Comment by alxproject** [comment]
it worked perfectly for my, I share my binary for linux x64

https://drive.google.com/open?id=1rk_Ko9aeGfT9FCy99VL8UBAfDWrZZNYN

latest node oracledb need node need node 10.16.0+

**Comment by igorklopov** [comment]
Thanks! The PR has some unnecessary indent changes (prettier?). Next time please provide as small patch as possible.

**Pull request closed without merging**
